# Generated by Django 5.1.7 on 2025-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditem_available_alter_fooditem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
    ]
