# Generated by Django 5.1.7 on 2025-03-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_fooditem_available_remove_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=10),
        ),
    ]
